language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
notifications:
  slack:
    secure: ETOaRGybfHJRBryqRfzblcgmKVBPcgj2DLVX75WPizWjx0faFXtujaE3H35bEooPiVqHO0CMC4Pvit7tr8A+jaqWV1JqZPpeX3HUj71OLJ7vhxCjosV+eNWgKCHtw1p3bGnowGHgsHxcOe/eT2xkku5y9/7CaR4ZLL7hGCOvGdJE2lm4KFs9NDagT/J+qn+UmVQmpbl122tpThvayo/XjSaRgjGZMF283ZwVieSfl2T21DIAJiQniAd+NDj65Ju33ZLZHFPShmdpBFJxbWgd2LjFtWidBoMbX+xoN3PpBdYj3xK+PqDzmC5hXWDdkhotm6GrD0PGIpITSTC2HZA8vWrv5aYwpncKKVJ1ZsKFcrWTc8qMO55l4WkgSgPnIzYldTr/I83LtGrWFXncjvFIj9z8bdzJniL6+tGlh13EHKfyHD0I2CIY9SShkVHWF7zQWdW0I1MWI+EulricmDg543jrVD0TeTGiFEtLYDZwothqkZBEgLw9I2YkC0NTSlGn+uOIxHKQOcpQ9QiQCM4JNjUjj9zL82SOuelzQOD6kIMArV0CE2t/XepoK/NPYRUkI7geNuKUs1rmPA2UgqUCdTo1kmo+3F1+tydiVSe9y8hK+autV4ZyG3ZRbL2wAN+hykx4wpAUgPL/Sl2vi/H01HZtxE6HemXTEMKcwqGDtx0=
